on:
  push:
    branches:
      - obsidian
      - ci
  pull_request:
    branches:
      - obsidian

env:
  CI: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        include:
          - { msystem: MINGW64, arch: x86_64, can-fail: false }
    runs-on:
      ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup MSYS2
        if: ${{ matrix.os == 'windows-latest' }}
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git 
            msys2-devel 
            base-devel 
            binutils 
            mingw-w64-${{ matrix.arch }}-toolchain
            mingw-w64-${{ matrix.arch }}-fltk
      - name: Install dependencies
        run: |
          if [ ${{ matrix.os }} = 'windows-latest' ]; then
            choco install fltk
          elif [ ${{ matrix.os }} = 'ubuntu-latest' ]; then
            sudo apt-get install libfltk1.3-dev
          elif [ ${{ matrix.os }} = 'macos-latest' ]; then
            brew install --verbose fltk
          fi
      - name: Configure with CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          cmake --build build -j 10
